#!/usr/bin/env python3
"""
NtupleForge CRAB Wrapper
=============================
This script runs on the worker node.
It prepares the environment and executes 'run_postproc.py'.
It robustly retrieves input files by reading the generated PSet.py.
"""

import os
import sys
import subprocess
import logging
import importlib.util
import json
from PhysicsTools.NanoAODTools.postprocessing.utils.crabhelper import runsAndLumis

# Setup Logging
logging.basicConfig(level=logging.INFO, format='[crab_script] : %(message)s')
logger = logging.getLogger("Wrapper")

def get_input_files_from_pset():
    """
    Reads the input file list from the PSet.py file generated by CRAB.
    This is more reliable than relying on sys.argv in some splitting modes.
    """
    pset_path = "PSet.py"
    if not os.path.exists(pset_path):
        logger.error(f"{pset_path} not found!")
        return []

    try:
        # Dynamically load PSet.py as a module
        spec = importlib.util.spec_from_file_location("PSet", pset_path)
        pset = importlib.util.module_from_spec(spec)
        spec.loader.exec_module(pset)
        
        # Extract the list of files from process.source.fileNames
        process = getattr(pset, "process", None)
        if process and hasattr(process, "source") and hasattr(process.source, "fileNames"):
            files = list(process.source.fileNames)
            logger.info(f"Extracted {len(files)} files from PSet.py")
            return files
        else:
            logger.error("Failed to extract fileNames from PSet.py")
            return []
    except Exception as e:
        logger.error(f"Error reading PSet.py: {e}")
        return []

def main():
    logger.info("="*60)
    logger.info(f"Wrapper Started on Host: {os.uname().nodename}")
    logger.info(f"Current Directory: {os.getcwd()}")
    logger.info("="*60)

    # ------------------------------------------------------------------
    # 1. Environment Setup
    # ------------------------------------------------------------------
    # CRAB flattens input files. We must add PWD to PYTHONPATH.
    cwd = os.getcwd()
    if "PYTHONPATH" in os.environ:
        os.environ["PYTHONPATH"] = f"{cwd}:{os.environ['PYTHONPATH']}"
    else:
        os.environ["PYTHONPATH"] = cwd

    # Also attempt to add 'script' directory if it exists (though usually flattened)
    if os.path.exists("script"):
        os.environ["PYTHONPATH"] = f"{cwd}/script:{os.environ['PYTHONPATH']}"

    logger.info(f"PYTHONPATH set to: {os.environ['PYTHONPATH']}")

    # ------------------------------------------------------------------
    # 2. Get Input Files
    # ------------------------------------------------------------------
    # Robustly retrieve input files from PSet.py
    input_files = get_input_files_from_pset()
    
    if not input_files:
        # Fallback: Check sys.argv if PSet extraction failed or was empty
        logger.warning("No files found in PSet.py, checking sys.argv...")
        for arg in sys.argv[2:]:
            if arg.endswith('.root'):
                input_files.append(arg)

    if not input_files:
        logger.error("CRITICAL: No input files found!")
        sys.exit(1)

    logger.info(f"Target Input Files: {input_files}")

    # ------------------------------------------------------------------
    # 3. Locate Main Script
    # ------------------------------------------------------------------
    script_name = "run_postproc.py"
    main_script = None

    if os.path.exists(script_name):
        main_script = script_name
        logger.info(f"Found main script in PWD: {main_script}")
    elif os.path.exists(f"script/{script_name}"):
        main_script = f"script/{script_name}"
        logger.info(f"Found main script in subfolder: {main_script}")
    else:
        logger.error(f"CRITICAL: {script_name} not found!")
        subprocess.run(["ls", "-R"])
        sys.exit(1)

    # ------------------------------------------------------------------
    # 4. Inject User Arguments
    # ------------------------------------------------------------------
    # We look for 'crab_args.txt' which contains flags like -b, -I, etc.
    args_file = "crab_args.txt"
    extra_flags = []

    if os.path.exists(args_file):
        logger.info(f"Loading arguments from {args_file}")
        try:
            with open(args_file, "r") as f:
                # Read lines, strip whitespace, and ignore empty lines
                for line in f:
                    clean_line = line.strip()
                    if clean_line:
                        extra_flags.append(clean_line)
        except Exception as e:
            logger.error(f"Failed to read args file: {e}")
            sys.exit(1)
            
    else:
        logger.warning(f"{args_file} not found. Running with defaults.")

    # ------------------------------------------------------------------
    # 5. CRAB run/lumi selection
    # ------------------------------------------------------------------
    # For Data, CRAB first applies config.Data.lumiMask and assigns the
    # certified run/lumi subset to this job. Forward that exact subset
    # to NanoAODTools PostProcessor via --json-input.
    try:
        crab_lumis = runsAndLumis()
    except Exception as e:
        logger.warning(f"Could not read CRAB run/lumi assignment: {e}")
        crab_lumis = {}

    if crab_lumis:
        lumi_json = "crab_lumis.json"
        with open(lumi_json, "w") as f:
            json.dump(crab_lumis, f, sort_keys=True)
        extra_flags.extend(["--json-input", lumi_json])
        logger.info(f"CRAB run/lumi selection written to {lumi_json}")
        logger.info(f"Run/lumi entries: {len(crab_lumis)} run(s)")
    else:
        logger.info("No CRAB run/lumi selection found (expected for MC).")

    # ------------------------------------------------------------------
    # 6. Execution
    # ------------------------------------------------------------------
    cmd = [sys.executable, main_script] + input_files + extra_flags
    
    logger.info("-" * 60)
    logger.info(f"Command: {' '.join(cmd)}")
    logger.info("-" * 60)

    try:
        # Flush buffers to ensure logs appear in order
        sys.stdout.flush()
        subprocess.run(cmd, check=True)
        logger.info("Post-processing completed successfully.")
    except subprocess.CalledProcessError as e:
        logger.error(f"Execution failed with exit code {e.returncode}")
        sys.exit(e.returncode)

if __name__ == "__main__":
    main()
